"""
Strict JSON schema for OpenAI Structured Outputs — MSEDCL bill extraction.

Schema field names match AI output; bill_validator aliases *_kw → internal keys.
"""

from __future__ import annotations

# OpenAI response_format json_schema payload
MSEDCL_BILL_JSON_SCHEMA: dict = {
    "name": "msedcl_bill_extraction",
    "strict": True,
    "schema": {
        "type": "object",
        "properties": {
            "consumer_name": {"type": ["string", "null"]},
            "consumer_number": {"type": ["string", "null"]},
            "billing_month": {"type": ["string", "null"]},
            "billing_period": {"type": ["string", "null"]},
            "billing_period_start": {"type": ["string", "null"]},
            "billing_period_end": {"type": ["string", "null"]},
            "previous_reading_date": {"type": ["string", "null"]},
            "current_reading_date": {"type": ["string", "null"]},
            "bill_date": {"type": ["string", "null"]},
            "due_date": {"type": ["string", "null"]},
            "address": {"type": ["string", "null"]},
            "tariff_category": {"type": ["string", "null"]},
            "meter_number": {"type": ["string", "null"]},
            "meter_serial_number": {"type": ["string", "null"]},
            "division": {"type": ["string", "null"]},
            "sub_division": {"type": ["string", "null"]},
            "tariff_code": {"type": ["string", "null"]},
            "contract_load_kw": {"type": ["number", "null"]},
            "connected_load_kw": {"type": ["number", "null"]},
            "sanctioned_load_kw": {"type": ["number", "null"]},
            "voltage": {"type": ["string", "null"]},
            "power_factor": {"type": ["number", "null"]},
            "billing_cycle": {"type": ["string", "null"]},
            "gst_number": {"type": ["string", "null"]},
            "previous_reading": {"type": ["number", "null"]},
            "current_reading": {"type": ["number", "null"]},
            "units_consumed": {"type": ["number", "null"]},
            "bill_amount": {"type": ["number", "null"]},
            "final_amount_payable": {"type": ["number", "null"]},
            "amount_payable": {"type": ["number", "null"]},
            "net_amount": {"type": ["number", "null"]},
            "current_bill_amount": {"type": ["number", "null"]},
            "amount_before_due_date": {"type": ["number", "null"]},
            "previous_balance": {"type": ["number", "null"]},
            "fixed_charges": {"type": ["number", "null"]},
            "energy_charges": {"type": ["number", "null"]},
            "fuel_adjustment": {"type": ["number", "null"]},
            "electricity_duty": {"type": ["number", "null"]},
            "tax_on_sale": {"type": ["number", "null"]},
            "monthly_history": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "month": {"type": "string"},
                        "units": {"type": ["number", "null"]},
                        "bill_amount": {"type": ["number", "null"]},
                    },
                    "required": ["month", "units", "bill_amount"],
                    "additionalProperties": False,
                },
            },
        },
        "required": [
            "consumer_name",
            "consumer_number",
            "billing_month",
            "billing_period",
            "billing_period_start",
            "billing_period_end",
            "previous_reading_date",
            "current_reading_date",
            "bill_date",
            "due_date",
            "address",
            "tariff_category",
            "meter_number",
            "meter_serial_number",
            "division",
            "sub_division",
            "tariff_code",
            "contract_load_kw",
            "connected_load_kw",
            "sanctioned_load_kw",
            "voltage",
            "power_factor",
            "billing_cycle",
            "gst_number",
            "previous_reading",
            "current_reading",
            "units_consumed",
            "bill_amount",
            "final_amount_payable",
            "amount_payable",
            "net_amount",
            "current_bill_amount",
            "amount_before_due_date",
            "previous_balance",
            "fixed_charges",
            "energy_charges",
            "fuel_adjustment",
            "electricity_duty",
            "tax_on_sale",
            "monthly_history",
        ],
        "additionalProperties": False,
    },
}
